version: "3.9"

services:
  web:
    build: .
    volumes:
      - ../:/workspaces/minimalreactmariadbapp
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
